[window]
decorations = "none"
opacity = 0.9

[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"
style  = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style  = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style  = "Italic"

[general]
import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]
