# Shared settings (both Windows + WSL)
[window]
opacity = 0.95
decorations = "None"


[selection]
save_to_clipboard = true

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
size = 14.0

[general]
import = [ "everforest.toml" ]
